### PR TITLE
update request to 2.74.x to patch vulnerability in 2.67.x

### PR DESCRIPTION
**Pull request by jshimko**
The current version of `request` that this package depends on has a vulnerability that has been patched in a later version.  This upgrades to the latest.

More info: https://snyk.io/vuln/npm:request:20160119

### CODE REVIEW

**Comment by jshimko** [comment]
Thanks!

**Comment by jshimko** [comment]
Would you mind pushing this update to NPM when you have a moment?  Thanks!

**Comment by aaronjudd** [comment]
@indexzero any news of when this will be pushed?  we need this dependency updated to get bunyan-loggly passing security checks...

**Comment by deyhle** [comment]
+1 for a new version on npm

**Comment by gavacho** [comment]
Need this published to npm

**Pull request merged**
