### PR TITLE
update dependency version for request package 2.75.x -> 2.79.x

### PR DESCRIPTION
**Pull request by kieckhafer**
Resolves issue #64
Fixes depreciated module (and warnings)

### CODE REVIEW

**Comment by inadarei** [comment]
This has been open for months and - nothing. Is this module abandoned?

**Comment by AlexTes** [comment]
@inadarei afraid so, I opened #68 two months back.

**Comment by tc** [comment]
can we get this merged?

**Comment by AlexTes** [comment]
@tc like I mentioned one comment up, winston is totally unmaintained, afraid you'll have to switch if you want something that's maintained.

**Pull request closed without merging**
